[package]
name = "ipv6"
version = "0.1.0"
authors = ["Ron Hashimoto <mail@h2so5.net>"]
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]
name = "ipv6"

[dependencies]
genet-derive = { path = "../../../genet-derive" }
genet-sdk = "0.5.0"
